### ISSUE TITLE
 Update Website & Documentation

### ISSUE THREAD

**Issue by PhrozenByte** [picocms/picocms.github.io#7]
@PhrozenByte commented [on 6 Feb 2016](https://github.com/picocms/Pico/issues/323#issue-131898969)

> This is a long-live issue to track and discuss wished updates of our website resp. documentation.

Please refer to picocms/Pico#323 for previous discussions.

#### Website

- [x] Add GitHub, Twitter and IRC icon to website
- [x] Add current version number to Download page
- [ ] Overhaul and extend `_development/` collection resp. `development.md`
- [ ] Improve `_cookbook/` collection resp. `cookbook.html`
  - Decide where to put links to it (inline user docs? website user docs? website dev docs?) and actually create the links
- [x] #358: Use [Webpaint `portfolio` ("Showcase")](http://themes.iki-bir.com/webpaint/multipage/full/portfolio.html) to re-implement `customization.md` with extended information about and screenshots of all plugins and themes
  - Use distinct data files (`_data/plugins.md` and `_data/themes.md`) to make adding plugins/themes much easier
  - See `phpDoc.html` and `_data/phpDoc.md` as a reference
- [ ] Look through the wiki to include more plugins and themes on Pico's website
- [ ] Decide where to put large source files, see https://github.com/picocms/Pico/pull/358#issuecomment-257721007 and following
- [x] Add a sane way to add "Read more..." pages (e.g. `upgrade.md` or `nginx.md` (#343))
- [x] #309: Add a phpDoc overview page
- [x] #345: Add extended nginx documentation
- [x] #349 + #352: Add "About Us" page
- [ ] #368: Create a "advanced asset handling" howto (allow access to certain files (matched by MIME type) in the `content/` folder)
- Decision to make: Replace `<h2>` headers with a [floating box](https://css-tricks.com/examples/PersistantHeaders/) in the TOC-reserved space on the left, see https://github.com/picocms/Pico/pull/349#issuecomment-220638496 for an example

#### Documentation

- [x] Add IRC to the "Getting Help" section
- [x] Add the "What information do we need" paragraph of the Issues section of our `CONTRIBUTING.md` to the "Getting Help" section
- [ ] Explain how to use Pico with `composer require picocms/Pico` and provide a appropriate `index.php`
  - Maybe create a distinct `pico-composer` project instead? See #317
- [ ] Pico 2.0: Update nginx rewrite rules in user docs/nginx details page
- [ ] Add a basic YAML tutorial/guide/howto
- [ ] Add a basic Markdown tutorial/guide/howto

**Comment by PhrozenByte** [comment]
New:
> - Add a basic YAML tutorial/guide/howto
> - Add a basic Markdown tutorial/guide/howto

**Comment by stefanocpp** [comment]
Hello! About improving cookbooks, I have a proposal about feed generation.
The code there puts everything up in the feed, while you might just want to push out new stories or articles.
I tried and used some code @PhrozenByte suggested some time ago to rule-out pages without a date or a `meta.unlisted`.

The idea is to replace
`{% for page in pages if page.id not in ['index','feed'] and not end %}`
with
`{% for page in pages if page.time and not page.meta.unlisted %}`
